matrix:
  include:
    - language: dart
      dart: stable
      install_dartium: true
      before_script:
        - cd webapp_angular
      dart_task:
        - test: --platform dartium

    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
