matrix:
  include:
    - language: java

      jdk:
        - oraclejdk8

      sudo: false

      script:
        - mvn clean verify

    - language: dart

      dart:
        - stable

      dart_task:
        - test: --platform dartium
          install_dartium: true
