matrix:
  include:
    - language: dart
      sudo: false
      dart: stable
      dist: trusty
      before_script:
        - cd $TRAVIS_BUILD_DIR/webapp-angular
      dart_task:
        - test: --platform dartium
          install_dartium: true


    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
