matrix:
  include:
    - language: dart
      dart:
        - stable
      install_dartium: true
      before_install:
        - cd $TRAVIS_BUILD_DIR/webapp_angular
      script:
        pub run test -p dartium test/

    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
