matrix:
  include:
    - language: dart
      sudo: false
      dart: stable
      dist: trusty
      install_dartium: true
      before_script:
        - cd $TRAVIS_BUILD_DIR/webapp-angular
        - pub get
      script:
        - pub run test -p dartium test/


    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
