matrix:
  include:
    - language: dart
      dart:
        - stable
      before_script:
        - cd webapp_angular
      dart_task:
        - test: --platform dartium
          install_dartium: true

    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
