language: java

jdk:
  - oraclejdk8

sudo: required

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - apt-get update

install:
  - sudo apt-get install dart

before_script:
  - export PATH=/usr/lib/dart/bin:$PATH

script:
  - mvn clean verify
  - cd webapp-angular
  - pub run test -p dartium test/
