matrix:
  include:
    - language: dart
      sudo: false
      dart: dev
      install_dartium: true
      before_install:
        - cd $TRAVIS_BUILD_DIR/webapp_angular
      dart_task:
        - test: --platform dartium

    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
