language: java

jdk:
  - oraclejdk8

sudo: required

before_install:
  - export DISPLAY=:99.0
install:
  - sudo apt-get install dart

script:
  - mvn clean verify
  - ./webapp-angular/test/test_script.sh
