matrix:
  include:
    - language: dart
      sudo: false
      dart: stable
      dist: trusty
      script:
        - set -e
        # Run the tests.
        - pub run test -p dartium test/


    - language: java
      jdk: oraclejdk8
      sudo: false
      script:
        - mvn clean verify
