name: webapp_angular
description: A dahsboard for the kapua gateway supply chain control simulation.
version: 0.0.1
#homepage: https://github.com/arthurdeschamps/kapua-iot-gateway-simulation
#author: arthurdeschamps <arthur.deschamps1208@gmail.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.1
  js: any
  logging: ^0.11.3+1
  chartjs: ^0.4.0
  dbscan: "^0.1.1"

dev_dependencies:
  angular_test: ^1.0.0-beta+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular2:
    entry_points: web/main.dart
- angular2/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
